version: "3.7"

services:
  app:
    container_name: application
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 80:8000
    volumes:
      - .:/application
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  postgres:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - .:/shared
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
  celery:
    build: ./server
    command: celery -A youtube_project worker -l info
    volumes:
      - .:/shared
    depends_on:
      - postgres
      - redis
  celery-beat:
    build: ./server
    command: celery -A youtube_project beat -l info
    volumes:
      - .:/shared
    depends_on:
      - postgres
      - redis
