version: "3.7"

services:
  app:
    container_name: application
    build:
      context: ./server
      dockerfile: Dockerfile
    links:
      - postgres
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/application
      - ~/.ssh:/root/.ssh
      - server-logs:/application/server/logs
      - server-site-packages:/usr/local/lib/python3.8/site-packages
      - server-usr-local-bin:/usr/local/bin
    command: python server/manage.py runserver 0:8000
    working_dir: /application
  postgres:
    image: postgres:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - .:/shared
      - postgres-data:/var/lib/postgresql/data
      - ./db_scripts:/docker-entrypoint-initdb.d/
volumes:
  server-site-packages:
    driver: local
  postgres-data:
    driver: local
  server-logs:
    driver: local
  server-usr-local-bin:
    driver: local
  redisdata:
    driver: local
