# Generated by Django 2.2.10 on 2021-06-17 06:30

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', encrypted_fields.fields.EncryptedCharField(max_length=255)),
                ('last_used', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'get_latest_by': 'published_at'},
        ),
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='published_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
