# Generated by Django 2.2.10 on 2021-06-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'get_latest_by': 'published_at'},
        ),
    ]
