# Generated by Django 2.2.10 on 2021-06-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_search', '0002_auto_20210617_0630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={},
        ),
        migrations.AlterField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(),
        ),
    ]
