# Generated by Django 2.2.10 on 2021-06-17 02:58

from django.db import migrations, models
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('video_search', '0002_auto_20210616_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', pgcrypto.fields.EncryptedTextField(charset='utf-8', check_armor=True, cipher='AES', unique=True, versioned=False)),
                ('last_used', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
