# Generated by Django 2.2.10 on 2021-06-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_search', '0003_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='published_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
