# Generated by Django 2.2.10 on 2021-06-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_search', '0003_auto_20210617_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(null=True),
        ),
    ]
